name: Java CI with Gradle

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK version 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 그래들 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      #gradle 권한 추가
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew


      - name: Set .yml for main
        run: |
          
          # main 설정 파일 디렉토리로 이동
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch ./application.yml
          
          echo "${{ secrets.MAIN_YML }}" > ./application.yml
        shell: bash



      # 빌드(테스트 스킵)
      - name: Build with Gradle
        run: ./gradlew build -x test

      # Spring 어플리케이션 Docker Image 빌드
      - name: Build Docker Image For Spring
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t leeseungryeol/gteam:1.0 .
          docker push leeseungryeol/gteam:1.0

      # 서버에서 Docker 이미지 실행
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            
            
            docker stop Gteam
            docker rm Gteam
            docker rmi leeseungryeol/gteam:1.0
            
            docker stop redis
            docker rm redis
            docker rmi redis
            docker pull leeseungryeol/gteam:1.0
            
            cd /
            docker-compose up -d
#            docker run -d -p 80:8080 --name Gteam leeseungryeol/gteam:1.0
